//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestimentAdvisor.Data.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RISK_AVAILABILITY
    {
        public int ID_RISK_AVAILABILITY { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
