//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestimentAdvisor.Data.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public int ID_USER { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string CPF { get; set; }
        public int NUMBER_CHILDREN { get; set; }
        public decimal VOLUM_AVAILABLE { get; set; }
        public int ID_RISK_AVAILABILITY { get; set; }
    }
}
