CREATE TABLE [dbo].[TB_RISK_AVAILABILITY] (
    [ID_RISK_AVAILABILITY] INT          NOT NULL,
    [DESCRIPTION]          VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID_RISK_AVAILABILITY] ASC)
);

CREATE TABLE [dbo].[TB_USER] (
    [ID_USER]              INT          NOT NULL,
    [NAME]                 VARCHAR (50) NOT NULL,
    [PASSWORD]             VARCHAR (50) NOT NULL,
    [EMAIL]                VARCHAR (50) NOT NULL,
    [CPF]                  NCHAR (10)   NOT NULL,
    [NUMBER_CHILDREN]      INT          NOT NULL,
    [VOLUM_AVAILABLE]      DECIMAL (18) NOT NULL,
    [ID_RISK_AVAILABILITY] INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_USER] ASC)
);