//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentAdvisor.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricInvestment
    {
        public int IdHistoricInvestment { get; set; }
        public int IdUser { get; set; }
        public int IdInvestment { get; set; }
        public decimal ValueInvested { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Investment Investment { get; set; }
        public virtual User User { get; set; }
    }
}
